### ISSUE TITLE
Document Shape - Kotlin

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#123]
Initial [design of the document shape](https://github.com/awslabs/smithy-kotlin/blob/main/docs/design/document-type.md) is already written in **smithy-kotlin**.

See also Smithy's [Simple Shapes section](https://awslabs.github.io/smithy/1.0/spec/core/model.html#simple-shapes) about document.

**Comment by aajtodd** [comment]
https://awslabs.github.io/smithy/1.0/spec/core/model.html#simple-shapes

See `Document` shape in the spec
