### ISSUE TITLE
Automatic pagination

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#124]
## Community Note
  1. Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
  2. Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
  3. If you are interested in working on this issue, please leave a comment
       
## Describe the feature
Provide API's that support automatic pagination of operations marked with the [paginated trait](https://awslabs.github.io/smithy/1.0/spec/core/behavior-traits.html#paginated-trait)

## Proposed Solution

See the proposed [design doc](https://github.com/awslabs/smithy-kotlin/blob/main/docs/design/paginators.md)

**Comment by aajtodd** [comment]
Note: `SdkAsyncIterable` ought to probably be renamed to `SdkAsyncSequence` since it is lazy like `Sequence` (`Iterable` on the other hand implies eager which it is not)

Update design as necessary when implementing to make this distinction clear.
