### ISSUE TITLE
Waiters Design

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Add support for generating waiters

## Additional Context       
https://awslabs.github.io/smithy/1.0/spec/waiters.html

*internal id*: 176179012

**Comment by ianbotsf** [comment]
The design has shipped and been implemented as part of #572. Resolving.
