### ISSUE TITLE
Consider usage of inline classes

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#133]
inline classes may be stable before dev preview release of SDK. We may have some use cases for it.

e.g. 

```
inline data class Region(val region: String)
```

https://blog.jetbrains.com/kotlin/2021/02/new-language-features-preview-in-kotlin-1-4-30/#inline-value-classes-stabilization

*internal id*: 177095028

**Comment by kiiadi** [comment]
assume you'd use `value classes` instead since they map to JVM value classes

**Comment by ianbotsf** [comment]
This may need more investigation to determine the exact benefit (i.e., why we'd do this).
