### ISSUE TITLE
Endpoint Discovery

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#146]
Design and implement dynamic endpoint discovery.

See also: 
    * [Endpoint discovery](https://awslabs.github.io/smithy/1.0/spec/aws/aws-core.html#client-endpoint-discovery)
    * /seps/accepted/shared/endpoint-discovery/
    * /seps/accepted/shared/sts_regionlization/

**Comment by ianbotsf** [comment]
Needs more investigation to determine whether this is still relevant.
