### ISSUE TITLE
HTTP interfaces spike

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#147]
This is more of just an idea in my head right now but I'm wondering if we can't make the HTTP primitives like request/response/HTTPRequestBuilder/etc interfaces.

The idea being that when using e.g. CRT as the HTTP engine we could be directly constructing CRT HTTP objects instead of copying to/from our own versions.

*internal id*: 176783073

**Comment by ianbotsf** [comment]
Probably won't get to this in the near-term.
