### ISSUE TITLE
Decide on kotlinx-datetime

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#182]
We currently generate our own _very_ basic version of `Instant` from the smithy-kotlin client runtime. We did this as a stop gap to get the protocols implememted (since most of the concern in the runtime and tests is around serialization/deserialization).

kotlinx-datetime went GA since then and we need to decide if we are going to adopt and use their MPP compatible version (and more feature complete) version of Instant or not. This will affect the public SDK types and will result in customers depending on this JetBrains library.

*internal id*: 174761718

**Comment by ianbotsf** [comment]
We need to better understand the timeline for stabilization to understand if it's realistic to depend on `kotlinx-datetime` by GA.

**Comment by jason-weddington** [comment]
We've decided not to use this and add wrappers later if needed.
