### ISSUE TITLE
Triage FIXMEs, TODOs, and ignored tests

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#191]
The existing sources should be grepped for remaining FIXME and TODOs in code.  For actual issues that should be addressed before GA: specific tickets should be created and the work should get done.  For comments that no longer seem valid or were asperational, they should be removed.

*internal id*: 176319865

**Comment by lauzadis** [comment]
Make sure to check internal code packages too

**Comment by ianbotsf** [comment]
Specifically:
* Remove OBE/irrelevant issues
* Prioritize issues, address high-priority ones in the near term
* Ensure issues/tasks exist for all items
