### ISSUE TITLE
Optimize Imports

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#194]
Look into optimizing how our imports are generated. We currently just dedupe them and possibly sort them. We can take this further by looking at how many symbols are pulled in from a particular subpackage and import * instead. Also if we are already importing * then we can remove any other explicit imports, etc.

Intellij does this as well with a threshold and optimizes your imports that way.

*internal id*: 176146357

**Comment by ianbotsf** [comment]
This is a codegen-only concern, not necessary to handle.
