### ISSUE TITLE
Codegen cleanup: unnecessary null handling 

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#195]
In protocol test codegen there are maybe 30 cases in restJson in which codegen produces null checks that are unneeded.  This task is to go through them and update codegen such that the unnecessary code isn't produced.

See also: #176146308

*internal id*: 176123118

**Comment by ianbotsf** [comment]
Resolving in favor of [aws-sdk-kotlin#322](https://github.com/awslabs/aws-sdk-kotlin/issues/322).
