### ISSUE TITLE
Enable JS KMP targets in smithy-kotlin RT.

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#197]
The smithy-kotlin runtime modules rely on our own gradle code to generate the necessary things for KMP.  Presently, this custom gradle code does not take JS platforms into account, and a consequence we cannot add JS specific implementation.

Acceptance criteria: am able to add JS target source trees to client runtime modules in smithy-kotlin.

*internal id*: 176041158

**Comment by ianbotsf** [comment]
Resolving in favor of [aws-sdk-kotlin#228](https://github.com/awslabs/aws-sdk-kotlin/issues/228).
