### ISSUE TITLE
Define Advanced HttpClient Config

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#198]
We generate service clients with the ability to specify an http client engine to use instead of the default. We currently don't take this into account in our generated close() call. 

Tasks are roughly:
* Implement some kind of SPI/loading from a factory rather than hard coding it. An example from ktor of what might work:
[common factory](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt#L42)
[jvm spi implementation](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/jvm/src/io/ktor/client/HttpClientJvm.kt#L42)
[native implementation](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/posix/src/io/ktor/client/engine/Loader.kt#L18)

* Update the generated `close()` method to take into account whether we manage the underlying `HttpClientEngine` or not to determine if we should close it. If a user passes a custom engine in - we do not own it and shouldn't close it on the user. They are expected to manage it's lifetime and cleanup any resources associated with it.

*internal id*: 176011935

**Comment by aajtodd** [comment]
We need the ability to expose protocol preference/alpn (e.g. if we need `h2` support from the service for event streams). CRT `TlsContext` exposes `alpn` which takes a raw string of `;` separated values (e.g. `h2;http/1.1`)

**Comment by aajtodd** [comment]
Splitting out into multiple tickets:
* https://github.com/awslabs/smithy-kotlin/issues/494
* https://github.com/awslabs/smithy-kotlin/issues/495
