### ISSUE TITLE
Add Pre-Signer

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#200]
Signing middleware was added in #174869571. This task would be to add a request pre-signer (the requirements of which I'm not clear on).

In addition the existing signer machinery should be broken out as a separate interface / type that customers can use standalone. The initial work in implementing the middleware did not expose any of the signing internals which is based on CRT.

Go SDK for example: https://github.com/aws/aws-sdk-go-v2/tree/59a6550f8efd29e142df8795578cae82ad6fe17c/aws/signer/v4

*internal id*: 176011716

**Comment by aajtodd** [comment]
presigners added by: https://github.com/awslabs/aws-sdk-kotlin/pull/257
general purpose signing function added in: https://github.com/awslabs/aws-sdk-kotlin/pull/318

Closing, re-open specific issues if necessary.
