### ISSUE TITLE
Enable explicit API mode

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#216]
Turn on explicit API mode:
https://kotlinlang.org/docs/reference/whatsnew14.html#explicit-api-mode-for-library-authors

We already turned this on as a warning in `aws-sdk-kotlin`. Fixing this is just tedious. Kyle and I also discussed at one point to make this a property and default to warning but turn on as an error during CI. This would allow local development to proceed uninhibited but require you to commit to what is public/private by the time you get to PR.

*internal id*: 174863447

**Comment by ianbotsf** [comment]
Implemented by the above PRs.
