### ISSUE TITLE
add JsonElement api

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy-kotlin#243]
We should consider adding something like gson/kotlinx.serialization/etc `JsonElement` that users can parse arbitrary JSON into. One of the motivating use cases is to not have to include a separate JSON library when using e.g. dynamodb and trying to load data from a json file and put a bunch of items into a table. 

e.g. https://docs.amazonaws.cn/en_us/amazondynamodb/latest/developerguide/GettingStarted.Java.02.html

We basically already have the definition since the [document](https://github.com/awslabs/smithy-kotlin/blob/main/client-runtime/client-rt-core/common/src/software/aws/clientrt/smithy/Document.kt#L11) type is basically what we are looking for.

Alternative would be to just add something like `Document.fromJson()`

**Comment by ianbotsf** [comment]
Not actionable, lacking customer feedback about use cases.
