### ISSUE TITLE
Determine what operational metrics we need to capture and track for SDK health

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#273]
For this task, we need to determine what metrics are important for us to consume (from somewhere) and monitor (alarms, dashboards) such that we are able to assess the health of the Kotlin SDK.  This would be both for general usage/updates as well as service-specific changes (trebuchet).

Some ideas (not necessarily what we want to track but here for examples):
* SDK published to public artifact repo (discrete event over time)
* SDK build time in Trebuchet
* Number of downloads from public artifact repositories (if available)

**Comment by ianbotsf** [comment]
Resolving in favor of [aws-sdk-kotlin#416](https://github.com/awslabs/aws-sdk-kotlin/issues/416).
