### ISSUE TITLE
DSL construction operator `invoke` ergonomics

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#290]
Currently our SDK uses DSL builder to create request instances.  This looks something like:

```
cloudFrontClient.createDistribution(CreateDistributionRequest.invoke {  })
```

This works but the `.invoke` part is unnecessary.  Ideally the IDE would generate code that did not include the function:

```
cloudFrontClient.createDistribution(CreateDistributionRequest {  })
```

Additionally when looking at properties that can be set in the builder, it is a little weird what the IDE suggests.  In the example above, there is a single property `distributionConfig` however the IDE suggests:

![Screenshot from 2021-04-23 17-06-42](https://user-images.githubusercontent.com/65979407/115940552-d1447780-a456-11eb-83be-c1fdb8386490.png)

**Comment by ianbotsf** [comment]
Seems like an IDE issue if anything. Nothing for Kotlin SDK to do here.
