### ISSUE TITLE
Implement support for `mediaType` trait (related to json-value)

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#332]
Related SEP: /packages/AwsDrSeps/blobs/master/--/seps/accepted/shared/json-value-trait.md

mediaType trait: https://awslabs.github.io/smithy/1.0/spec/core/protocol-traits.html?highlight=media#mediatype-trait

**Comment by ianbotsf** [comment]
No plans to tackle this for now, json-value data will be handled as strings.
