### ISSUE TITLE
remove special treatment of restXml Errors

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy-kotlin#350]
Both the XML deserializer and the (rest)XML serde descriptor generator in codegen special case errors. 

We should lift the special casing/handling of errors to the protocol implementation itself.

Do this after #127 which has better support for targeting specific serializer/deserializers and extending/overriding their implementation

High level:
* Remove the `XmlError` trait from the `serde-xml` package
* Remove the `Error` name specializations in the `XmlSerdeDescriptorGenerator`. Force protocols to override the base serde descriptor generator to do this kind of descriptor customization.
* Use [restXml.noErrorWrapping](https://awslabs.github.io/smithy/1.0/spec/aws/aws-restxml-protocol.html#aws-protocols-restxml-trait) property to determine if we need to unwrap an error
    * If so generate code to unwrap the top-level tag inline. See how this is done in the AWS query protocol implementation which must unwrap all responses. 

We may also be able to revert back to actually validating the root element. We turned it off in #289 because S3 has returned responses that do not match the model. This was/is considered an error in the model though and should be fixed in any S3 model generated after 5/14. We may still want to leave this behavior on "just in case".

**Comment by ianbotsf** [comment]
Internal-only concern, no plans to address as of now.
