### ISSUE TITLE
Inconsistency with GetCityInput and GetCityImageInput in domain class types doc

### ISSUE THREAD

**Issue by bkrichards** [awslabs/smithy-kotlin#471]
The documentation for domain class types uses different names for the same class throughout the doc and makes it confusing.

## Describe the issue
Use `GetCityInput` or `GetCityImageInput` in all the sample code for consistency

## Links
https://github.com/awslabs/smithy-kotlin/blob/main/docs/design/domain-class-types-in-kotlin-sdk.md

**Comment by kggilmer** [comment]
Thanks for the feedback @bkrichards .
