### ISSUE TITLE
HTTP Client Engine SPI/Auto load

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy-kotlin#495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Describe the Feature

Implement SPI support for `HttpClientEngine`. This would allow generated clients to not necessarily take a hard dependency on a specific HTTP client engine. Instead codegen could generate something like:

```kotlin

val engine = config.engine ?: sdkHttpClient(/* engine loaded automatically or throw if none found */) {
     // configure common engine properties
} 

```

An example of what ktor does to support KMP is here:
* [common factory](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/common/src/io/ktor/client/HttpClient.kt#L42)
* [jvm spi implementation](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/jvm/src/io/ktor/client/HttpClientJvm.kt#L42)
* [native implementation](https://github.com/ktorio/ktor/blob/master/ktor-client/ktor-client-core/posix/src/io/ktor/client/engine/Loader.kt#L18)
    * [example](https://github.com/ktorio/ktor/blob/main/ktor-client/ktor-client-curl/desktop/src/io/ktor/client/engine/curl/Curl.kt#L30-L40) of curl engine registering itself using init hook

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by aajtodd** [comment]
This would also be useful for the runtime to not have to depend on an explicit engine (e.g. `ImdsClient`, credential providers, etc)

**Comment by ianbotsf** [comment]
This path forward is no longer favored. Resolving in favor of a different task to provide an explicit default artifact (#602).
