### ISSUE TITLE
Validate usage of Service.version

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy-kotlin#517]
Smithy 1.13 relaxes the Service shape to not require a `version`

> the version property of a `service` can now return an empty string as it has been made `optional`

This shouldn't affect AWS SDKs since it will still be required but it may change what we can/should generate for a non-AWS SDK use case. 

Task here is to see where we assume version is present and update usage as necessary

**Comment by ianbotsf** [comment]
No action required here.
