### ISSUE TITLE
Publish test reports as part of CI builds

### ISSUE THREAD

**Issue by kggilmer** [awslabs/smithy-kotlin#522]
Sometimes there are test failures that emerge in CI.  The test reports are not saved after the container executing the CI job completes.  Sometimes it's helpful to read the report to determine the root cause of the issue. 

* Acceptance Criteria
As a CI user, I am able to read the unit test reports generated by the build in the test phase, after the CI workflow completes.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue, please leave a comment

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by aajtodd** [comment]
https://github.com/marketplace/actions/publish-unit-test-results

I think the hardest part of this is getting all the tests into a single report. We have a `rootAllTest` task which IIRC was supposed to do this but I'm not sure if it actually works anymore (or ever did for that matter).

**Comment by ianbotsf** [comment]
No plan to implement for now, resolving.
