### ISSUE TITLE
Refactor synthetic traits to use builtin input and output traits

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy-kotlin#546]
Next version of smithy (1.15+) will have support for [builtin input and output traits](https://github.com/awslabs/smithy/pull/980). We currently generate these as synthetic traits and should make use of the new functionality to be forwards compatible with Smithy 2.0 (rules around `input` and `output` structures will be different than other structures in 2.0 regarding `@required` or default value)

This also introduced a new `Unit` type which signifies an operation really truly doesn't have an input or output. It will be considered a breaking change to go from `Unit` to having an input or output which will allow us to generate operations targeting `Unit` without a synthetic input or output type.

**Comment by ianbotsf** [comment]
We already have a customization in place to deal with synthetic shape generation.
