### ISSUE TITLE
Bind to OkHttp Engine Directly

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy-kotlin#629]
Add a new `http-client-engine-okhttp` artifact which binds to OkHTTP engine directly (rather than using `KtorEngine` + `ktor-engine-okhttp`). Replace the default HTTP engine with this new abstraction (the default is already OkHTTP, it's just going through ktor abstraction layer).

This should allow us to access the duplex stream API's which is one of the things still blocking event streams (the other is event stream signing). 

Longer term it looks like OkHTTP 5 may support KMP which would allow us to use the same default engine potentially across all/multiple KMP targets.

**Comment by FredyH** [comment]
Ktor recently updated to version 2.0 which changed a lot of package locations and renamed a bunch of things.  When mixing dependencies between Ktor 1.x and Ktor 2.0 this will lead to linker errors during runtime which currently prevents me from using the Kotlin AWS client in my Ktor 2.0 project.
I think this change would completely bypass the issue while sacrificing no functionality.

**Comment by aajtodd** [comment]
@FredyH Thanks for weighing in.

This unfortunately won't completely solve the issue. We still have a reliance on `ByteReadChannel` from `ktor-io`. This issue is more about being able to get at all the capability that `okhttp` provides. `ktor` exposes a common subset of capability across different implementations and this unfortunately means that sometimes the more advanced/nuanced features are not accessible.  

That particular issue is being tracked in https://github.com/awslabs/aws-sdk-kotlin/issues/480

Feel free to comment there or upvote.
