### ISSUE TITLE
API request with a URI path containing XML characters not escaped properly for signature calculation

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/smithy-kotlin#657]
## Describe the bug

Some requests to services fail with signature validation errors if the request contains a URI path with XML characters (e.g., `<`, `>`, `/`).

## Expected Behavior

The request should sign correctly and be accepted by the remote service.

## Current Behavior

An incorrect signature is calculated and the service throws an error:

> The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.

## Steps to Reproduce

```kotlin
Route53Client
    .fromEnvironment { }
    .getHealthCheck { healthCheckId = "foo<bar>baz</bar>" }
```

NOTE: For this example request, the canonical string to sign is calculated as:

```
GET
/2013-04-01/healthcheck/foo%3Cbar%3Ebaz%3C%2Fbar%3E

amz-sdk-invocation-id:4cedbe96-7821-4b72-ab59-6d7b1c284ea8
amz-sdk-request:attempt=1; max=3
host:route53.amazonaws.com
x-amz-date:20220606T221442Z
x-amz-user-agent:aws-sdk-kotlin/0.16.2-SNAPSHOT

amz-sdk-invocation-id;amz-sdk-request;host;x-amz-date;x-amz-user-agent
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

## Possible Solution

Not yet known.

## Context

Discovered during execution of pen test.

## Your Environment
Amazon Linux 2 
OpenJDK 1.8.0_312-b07
AWS SDK for Kotlin 0.16.2-SNAPSHOT

**Comment by ianbotsf** [comment]
For reference, the classic CRT signer produces this canonical string to sign:

```
GET
/2013-04-01/healthcheck/foo%253Cbar%253Ebaz%253C%252Fbar%253E

amz-sdk-invocation-id:d5476d1f-3008-41bf-9376-3241e386732f
amz-sdk-request:attempt=1; max=3
host:route53.amazonaws.com
x-amz-date:20220606T224131Z
x-amz-user-agent:aws-sdk-kotlin/0.16.2-SNAPSHOT

amz-sdk-invocation-id;amz-sdk-request;host;x-amz-date;x-amz-user-agent
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Note that the encoding of the path differs:

* `foo%3Cbar%3Ebaz%3C%2Fbar%3E` (default signer)
* `foo%253Cbar%253Ebaz%253C%252Fbar%253E` (CRT signer)

**Comment by aajtodd** [comment]
looks like `useDoubleUriEncode` isn't respected perhaps?

I don't see `useDoubleUriEncode` or `normalizeUriPath` covered in the test suite. We should consider adding coverage and extending `context.json` as necessary.
