### ISSUE TITLE
Add support for Smithy IDLv 2.0 default trait

### ISSUE THREAD

**Issue by ianbotsf** [awslabs/smithy-kotlin#718]
Add support for the [defaultTrait](https://smithy.io/2.0/spec/type-refinement-traits.html#default-trait). 
 * In particular we may want to update our codegen constructs which are currently based on things like `@boxed` and primitive value types for figuring out defaults and nullability. We should revamp this to be much clearer and to align to IDL2 ([example](https://github.com/awslabs/smithy-kotlin/blob/cfa0fd3a30b4c50b75485786f043d4e2ad803f55/smithy-kotlin-codegen/src/main/kotlin/software/amazon/smithy/kotlin/codegen/model/SymbolExt.kt#L43)). This will require using the nullability index (possibly in more places than we do now).
* `@box` trait was deprecated, update tests/codegen to use [default](https://smithy.io/2.0/guides/migrating-idl-1-to-2.html#converting-primitive-root-level-shapes-from-1-0) trait instead
* ~~Implement [presence tracking](https://smithy.io/2.0/spec/type-refinement-traits.html#default-value-serialization)~~

**Comment by ianbotsf** [comment]
Support Smithy IDL v2, including int enums, full nullability support via presence tracking, and any other new features available (requires investigation).

**Comment by aajtodd** [comment]
Presence tracking: https://smithy.io/2.0/spec/type-refinement-traits.html#default-value-serialization

**Comment by aajtodd** [comment]
I've split this catch all Smithy IDL v2 issue out into multiple issues (noted in comment above). I've left this issue dedicated to supporting the `@default` trait in Smithy IDL v2
