### ISSUE TITLE
Fix HttpClientEngineConfiguration mapping to OkHttp Engine

### ISSUE THREAD

**Issue by aajtodd** [awslabs/smithy-kotlin#744]
There are several fields in our [HttpClientEngineConfig](https://github.com/awslabs/smithy-kotlin/blob/main/runtime/protocol/http/common/src/aws/smithy/kotlin/runtime/http/engine/HttpClientEngineConfig.kt#L19) that are not implemented correctly by the OkHttpEngine.

In particular:
* `maxConnections` -> There isn't really an exact equivalent to this. The closest approximation will be to implement a custom `Dispatcher` and pass it to the engine at construction. In particular setting the `maxRequests` and `maxRequestPerHost` appropriately on the [Dispatcher](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-dispatcher/#properties)
    * `maxRequestPerHost` has no explicit configuration knob yet but it is called out in the reference architecture in section 3 (`ConnectionManagerConfiguration.maxConcurrency`). We should also investigate if we should expose this knob directly and map it to the dispatcher (and to whatever the CRT engine equivalent is). If not this should probably be defaulted to the same value as `maxConnections`. 

According to OkHttp authors to mark a connection as not re-usable:
  > Add a header, Connection: close on either the request or response. This can be done in an interceptor.

We have [need](https://github.com/awslabs/aws-sdk-kotlin/issues/696) for exposing an API like this on `HttpResponse/Call` 

From the referenced S3 docs on retrying:
> When you retry a request, we recommend using a new connection to Amazon S3 and performing a fresh DNS lookup. 

I think there are likely other cases where a retry may need/want to force a new connection. We should also investigate engines if we can expose a (e.g.) `noNewExchangesOnConnection()` API

**Comment by ianbotsf** [comment]
The parts about mapping connections configurations to OkHttp were completed in #795. The parts about supporting connection closure on retry will be handled in #745 and [aws-sdk-kotlin#696](https://github.com/awslabs/aws-sdk-kotlin/issues/696).
